import {
  Home,
  Plane,
  ShoppingBag,
  Utensils,
  Repeat,
} from "lucide-react";

export const budgets = [
  {
    title: "Food & Dining",
    subtitle: "Active Monthly Budget",
    spent: "₹84,250",
    limit: "₹1,20,000",
    percentage: 70,
    icon: Utensils,
    size: "large",
    tone: "green",
  },
  {
    title: "Rent & Housing",
    subtitle: "Monthly fixed cost",
    spent: "₹2,45,000",
    limit: "₹2,45,000",
    percentage: 100,
    icon: Home,
    size: "medium",
    tone: "green",
    badge: "Fixed",
  },
  {
    title: "Travel",
    subtitle: "Includes commute & leisure",
    spent: "₹48,500",
    limit: "₹50,000",
    percentage: 97,
    icon: Plane,
    size: "small",
    tone: "red",
    badge: "Critical",
    warning: "You are ₹1,500 away from your limit.",
  },
  {
    title: "Shopping",
    subtitle: "Personal purchases",
    spent: "₹12,000",
    limit: "₹40,000",
    percentage: 30,
    icon: ShoppingBag,
    size: "small",
    tone: "muted",
  },
  {
    title: "Subscriptions",
    subtitle: "Recurring services",
    spent: "₹8,200",
    limit: "₹10,000",
    percentage: 82,
    icon: Repeat,
    size: "small",
    tone: "muted",
  },
];