# Generated by Django 5.2.14 on 2026-06-11 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(blank=True, db_index=True, editable=False, max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('notification_type', models.CharField(choices=[('budget', 'Budget'), ('goal', 'Goal'), ('report', 'Report'), ('subscription', 'Subscription'), ('ai_alert', 'AI Alert'), ('transaction', 'Transaction')], max_length=30)),
                ('tone', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('dark', 'Dark'), ('purple', 'Purple'), ('muted', 'Muted')], default='dark', max_length=20)),
                ('action_label', models.CharField(blank=True, max_length=80, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('progress', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
