# Generated by Django 5.2.14 on 2026-05-30 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_id', models.CharField(blank=True, db_index=True, editable=False, max_length=30, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('is_stale', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insight_snapshots',
            },
        ),
    ]
