# Generated by Django 5.2.14 on 2026-08-08 01:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insightsnapshot',
            options={'ordering': ['-generated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='insightsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insightsnapshot',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='insightsnapshot',
            name='period_end',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='insightsnapshot',
            name='period_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='insightsnapshot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='insightsnapshot',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='insightsnapshot',
            name='is_stale',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='insightsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='insightsnapshot',
            index=models.Index(fields=['user', 'is_stale'], name='insight_sna_user_id_7cedca_idx'),
        ),
        migrations.AddIndex(
            model_name='insightsnapshot',
            index=models.Index(fields=['user', 'status'], name='insight_sna_user_id_3c01ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='insightsnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'period_start', 'period_end'), name='unique_user_insight_period'),
        ),
    ]
