# Generated by Django 5.2.14 on 2026-08-09 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_alter_insightsnapshot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='insightsnapshot',
            new_name='insight_user_stale_idx',
            old_name='insight_sna_user_id_7cedca_idx',
        ),
        migrations.RenameIndex(
            model_name='insightsnapshot',
            new_name='insight_user_status_idx',
            old_name='insight_sna_user_id_3c01ca_idx',
        ),
        migrations.AddIndex(
            model_name='insightsnapshot',
            index=models.Index(fields=['user', 'period_start', 'period_end'], name='insight_user_period_idx'),
        ),
    ]
