# Generated by Django 5.0.6 on 2026-05-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_source',
            field=models.CharField(choices=[('rule', 'Rule'), ('ai', 'AI'), ('user', 'User'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
