# Generated by Django 5.2.14 on 2026-05-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_category_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_vectorized',
            field=models.BooleanField(default=False),
        ),
    ]
