# Generated by Django 5.2.14 on 2026-07-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactionembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_is_estimated',
            field=models.BooleanField(default=False),
        ),
    ]
