# Generated by Django 5.2.14 on 2026-07-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='parser_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parser_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
