# Generated by Django 5.2.14 on 2026-08-18 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('transactions', '0009_alter_transaction_date'),
        ('uploads', '0005_uploadedfile_processing_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='banking.bankconnection'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('upload', 'Upload'), ('bank_sync', 'Bank Sync'), ('manual', 'Manual'), ('csv_import', 'CSV Import')], default='upload', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('bank_connection__isnull', False), ('external_transaction_id__isnull', False)), fields=('bank_connection', 'external_transaction_id'), name='unique_bank_external_transaction'),
        ),
    ]
