# Generated by Django 5.2.14 on 2026-06-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_goal_goal_type_alter_goal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='ai_recommendations_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
