# Generated by Django 5.2.14 on 2026-06-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_ai_recommendations_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('debt', 'Debt'), ('purchase', 'Purchase'), ('travel', 'Travel'), ('investment', 'Investment'), ('other', 'Other')], default='savings', max_length=30),
        ),
    ]
