# Generated by Django 5.2.14 on 2026-06-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goal_goal_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='is_priority',
        ),
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
