# Generated by Django 5.0.6 on 2026-05-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='upload_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30, unique=True),
        ),
    ]
