# Generated by Django 5.0.6 on 2026-05-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_uploadedfile_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
