# Generated by Django 5.2.14 on 2026-05-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_uploadedfile_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='ai_tip_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='ai_tip_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='ai_tip_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
