# Generated by Django 5.2.14 on 2026-05-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_uploadedfile_ai_tip_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_step',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
