ALLOWED_CATEGORIES = [
    "Food",
    "Groceries",
    "Transport",
    "Fuel",
    "Shopping",
    "Rent",
    "Utilities",
    "Subscriptions",
    "Salary",
    "Bank Fees",
    "Healthcare",
    "Insurance",
    "Investments",
    "Travel",
    "Entertainment",
    "Education",
    "Income",
    "Cash Withdrawal",
    "Uncategorized",
]