from ai_engine.categorization.category_constants import ALLOWED_CATEGORIES

CATEGORY_RULES = {
    "Bank Fees": [
        "account fee",
        "paper stmnt fee",
        "statement fee",
        "monthly fee",
        "service charge",
        "bank charge",
        "fee waiver",
        "maintenance fee",
        "processing fee",
        "late fee",
        "annual fee",
        "bank fee",
        "atm fee",
        "overdraft",
        "minimum balance fee",
        "sms charge",
    ],

    "Salary": [
        "salary",
        "payroll",
        "biweekly payment",
        "direct deposit",
        "salary credit",
        "monthly salary",
        "pay credit",
        "bonus",
        "incentive",
        "stipend",
        "employee payment",
        "wages",
        "income credit",
    ],

    "Fuel": [
        "petrol",
        "fuel",
        "gas station",
        "diesel",
        "indian oil",
        "bharat petroleum",
        "hp petrol",
        "fuel station",
        "shell",
        "ioc",
    ],

    "Utilities": [
        "electric",
        "electricity",
        "bescom",
        "water bill",
        "utility",
        "mobile phone",
        "phone bill",
        "broadband",
        "internet",
        "wifi",
        "airtel",
        "jio fiber",
        "vodafone",
        "electric bill",
        "power bill",
        "gas bill",
        "recharge",
        "postpaid",
        "prepaid",
    ],

    "Rent": [
        "rent",
        "apartment rent",
        "house rent",
        "flat rent",
        "lease",
        "rental payment",
        "property rent",
        "monthly rent",
    ],

    "Shopping": [
        "amazon",
        "flipkart",
        "myntra",
        "store",
        "shopping",
        "electronics",
        "purchase",
        "retail",
        "nike",
        "adidas",
        "mall",
        "invoice",
        "online order",
        "order payment",
        "shopping cart",
        "jewelers",
    ],

    "Food": [
        "restaurant",
        "coffee",
        "swiggy",
        "zomato",
        "deli",
        "cafe",
        "food order",
        "pizza",
        "burger",
        "starbucks",
        "dominos",
        "kfc",
        "mcdonald",
        "eatery",
        "dining",
        "food delivery",
        "meal",
        "snacks",
    ],

    "Groceries": [
        "bigbasket",
        "dmart",
        "grocery",
        "groceries",
        "supermarket",
        "mart",
        "daily needs",
        "vegetables",
        "milk",
        "provisions",
        "fresh market",
        "reliance fresh",
    ],

    "Transport": [
        "uber",
        "ola",
        "metro",
        "cab",
        "taxi",
        "bus",
        "train",
        "transport",
        "ride",
        "commute",
        "auto",
        "rapido",
        "parking",
        "toll",
    ],

    "Travel": [
        "airbnb",
        "hotel",
        "flight",
        "travel",
        "airlines",
        "airport",
        "booking",
        "trip",
        "vacation",
        "indigo",
        "vistara",
        "goibibo",
        "makemytrip",
        "oyo",
        "resort",
        "stay",
    ],

    "Subscriptions": [
        "netflix",
        "spotify",
        "youtube premium",
        "apple icloud",
        "subscription",
        "recurring billing",
        "monthly subscription",
        "prime membership",
        "aws",
        "chatgpt",
        "openai",
        "adobe",
        "canva",
        "figma",
        "google one",
        "membership",
        "icloud",
        "saas",
    ],

    "Healthcare": [
        "apollo",
        "pharmacy",
        "hospital",
        "medicine",
        "consultation",
        "doctor",
        "clinic",
        "healthcare",
        "medical",
        "lab test",
        "diagnostic",
        "tablet",
        "health checkup",
    ],

    "Insurance": [
        "insurance",
        "policy",
        "premium",
        "life insurance",
        "medical insurance",
        "vehicle insurance",
        "lic",
        "health insurance",
    ],

    "Investments": [
        "mutual fund",
        "sip",
        "stock",
        "investment",
        "zerodha",
        "groww",
        "upstox",
        "dividend",
        "equity",
        "crypto",
        "coinbase",
        "etf",
        "trading",
    ],

    "Entertainment": [
        "movie",
        "cinema",
        "theatre",
        "concert",
        "gaming",
        "game",
        "steam",
        "playstation",
        "xbox",
        "entertainment",
        "event ticket",
    ],

    "Education": [
        "udemy",
        "coursera",
        "course",
        "education",
        "tuition",
        "college",
        "school",
        "training",
        "certification",
        "workshop",
        "learning",
    ],

    "Cash Withdrawal": [
        "cash withdrawal",
        "atm",
        "cash dispense",
        "cash wd",
        "withdrawal",
        "atm withdrawal",
    ],

    "Income": [
        "refund",
        "cashback",
        "interest credit",
        "rebate",
        "reward",
        "credit received",
    ],
}

for category in CATEGORY_RULES.keys():
    if category not in ALLOWED_CATEGORIES:
        raise ValueError(f"{category} missing from ALLOWED_CATEGORIES")