# Generated by Django 5.2.14 on 2026-05-23 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, db_index=True, editable=False, max_length=40, unique=True)),
                ('merchant', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('transactions_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('detected', 'Detected'), ('manual', 'Manual')], default='detected', max_length=20)),
                ('status', models.CharField(choices=[('detected_once', 'Detected Once'), ('recurring', 'Recurring')], default='detected_once', max_length=30)),
                ('smart_reminder', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['merchant'],
                'unique_together': {('user', 'merchant')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmed'), ('ignored', 'Ignored'), ('cancel_candidate', 'Cancel Candidate')], default='active', max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_preferences',
                'unique_together': {('user', 'subscription')},
            },
        ),
    ]
