# Generated by Django 5.0.6 on 2026-05-16 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_savings_target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spending_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('housing_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('groceries_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('entertainment_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('priorities', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
