# Generated by Django 5.2.14 on 2026-08-18 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_code', models.CharField(max_length=50)),
                ('institution_name', models.CharField(max_length=150)),
                ('account_name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('credit', 'Credit'), ('other', 'Other')], default='savings', max_length=30)),
                ('masked_account_number', models.CharField(max_length=20)),
                ('external_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('syncing', 'Syncing'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='connected', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_connections',
                'constraints': [models.UniqueConstraint(fields=('user', 'institution_code', 'external_account_id'), name='unique_user_bank_account')],
            },
        ),
    ]
