# Generated by Django 5.2.14 on 2026-08-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankconnection',
            name='provider',
            field=models.CharField(choices=[('demo', 'Demo')], default='demo', max_length=50),
        ),
    ]
